[package]
name = "dashmap"
version = "6.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
rust-version = "1.67"
license = "MIT"
repository = "https://github.com/xacrimon/dashmap"
homepage = "https://github.com/xacrimon/dashmap"
description = "Blazing fast concurrent HashMap for Rust."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[features]
default = []
raw-api = []
inline = ["hashbrown/inline-more"]

rayon = ["dep:rayon"]
serde = ["dep:serde"]
typesize = ["dep:typesize"]

[dependencies]
lock_api = "0.4.10"
parking_lot_core = "0.9.8"
hashbrown = { version = "0.15.0", default-features = false }
serde = { version = "1.0.188", optional = true, features = ["derive"] }
rayon = { version = "1.7.0", optional = true }
once_cell = "1.18.0"
arbitrary = { version = "1.3.0", optional = true }
crossbeam-utils = "0.8"
typesize = { version = "0.1.8", default-features = false, optional = true }
replace_with = "0.1.7"
polonius-the-crab = "0.4.2"

[package.metadata.docs.rs]
features = ["rayon", "raw-api", "serde"]
